- repo: local
  hooks:
    - id: ruff-format
      name: ruff-format
      entry: poetry run ruff format
      language: system
      types: [python]
    - id: ruff
      name: ruff
      entry: poetry run ruff check --fix
      language: system
      types: [python]
