FROM docker.io/library/python:3.12-slim AS builder

RUN apt-get update -y && apt-get install -y gcc git && rm -rf /var/lib/apt/lists/*
RUN python -m pip install --upgrade pip setuptools uv

WORKDIR /app
ENV UV_CACHE_DIR=/tmp/uv-cache

COPY pyproject.toml uv.lock ./
RUN uv sync --no-install-project

COPY . .
RUN uv sync

FROM docker.io/library/python:3.12-slim

RUN apt-get update -y && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir uv

WORKDIR /app
COPY --from=builder --chown=1000:1000 /app /app

USER 1000
ENV UV_CACHE_DIR=/tmp/uv-cache

EXPOSE 5001

ENTRYPOINT ["uv", "run", "uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "5001"]
