import { Icon } from "@equinor/eds-core-react";
import {
    accessible,
    account_circle,
    add,
    arrow_back,
    autorenew,
    battery,
    battery_alert,
    battery_charging,
    battery_unknown,
    check_circle_outlined,
    chevron_down,
    chevron_right,
    clear,
    cloud_off,
    collapse,
    copy,
    delete_to_trash,
    do_not_disturb,
    done,
    edit,
    email,
    error_outlined,
    expand,
    external_link,
    file_description,
    fullscreen,
    fullscreen_exit,
    help_outline,
    history,
    info_circle,
    image,
    library_books,
    log_out,
    notifications,
    pause_circle,
    pause_circle_outlined,
    play_circle,
    power_button,
    pressure,
    remove_outlined,
    save,
    stop_circle,
    time,
    toolbox,
    undo,
    view_list,
    warning_outlined,
} from "@equinor/eds-icons";

Icon.add({
    accessible,
    account_circle,
    add,
    arrow_back,
    autorenew,
    battery,
    battery_alert,
    battery_charging,
    battery_unknown,
    check_circle_outlined,
    chevron_down,
    chevron_right,
    clear,
    cloud_off,
    collapse,
    copy,
    delete_to_trash,
    do_not_disturb,
    done,
    edit,
    email,
    error_outlined,
    expand,
    external_link,
    file_description,
    fullscreen,
    fullscreen_exit,
    help_outline,
    history,
    info_circle,
    image,
    library_books,
    log_out,
    notifications,
    pause_circle,
    pause_circle_outlined,
    play_circle,
    power_button,
    pressure,
    remove_outlined,
    save,
    stop_circle,
    time,
    toolbox,
    undo,
    view_list,
    warning_outlined,
});

export enum Icons {
    Accessible = "accessible",
    Account = "account_circle",
    Add = "add",
    ArrowBack = "arrow_back",
    Autorenew = "autorenew",
    Battery = "battery",
    BatteryAlert = "battery_alert",
    BatteryCharging = "battery_charging",
    BatteryUnknown = "battery_unknown",
    Check = "check_circle_outlined",
    ChevronDown = "chevron_down",
    ChevronRight = "chevron_right",
    Clear = "clear",
    CloudOff = "cloud_off",
    Collapse = "collapse",
    Copy = "copy",
    DeleteToTrash = "delete_to_trash",
    DoNotDisturb = "do_not_disturb",
    Done = "done",
    Edit = "edit",
    Email = "email",
    ErrorOutlined = "error_outlined",
    Expand = "expand",
    ExternalLink = "external_link",
    Failed = "error_outlined",
    FileDescription = "file_description",
    Fullscreen = "fullscreen",
    FullscreenExit = "fullscreen_exit",
    HelpOutline = "help_outline",
    Historic = "history",
    InfoCircle = "info_circle",
    Image = "image",
    LibraryBooks = "library_books",
    LogOut = "log_out",
    Notifications = "notifications",
    PauseButton = "pause_circle",
    Pause = "pause_circle_outlined",
    PlayButton = "play_circle",
    PowerButton = "power_button",
    Pressure = "pressure",
    Remove = "remove_outlined",
    Save = "save",
    StopButton = "stop_circle",
    Pending = "time",
    Time = "time",
    Toolbox = "toolbox",
    Undo = "undo",
    ViewList = "view_list",
    Warning = "warning_outlined",
}
